<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sidecar/config_service.proto

namespace Oat\Envmgmt\Sidecar;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.sidecar.GetConfigRequest</code>
 */
class GetConfigRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tenant_id = 1 [json_name = "tenantId"];</code>
     */
    protected $tenant_id = '';
    /**
     * Generated from protobuf field <code>string configuration_id = 2 [json_name = "configurationId"];</code>
     */
    protected $configuration_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tenant_id
     *     @type string $configuration_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sidecar\ConfigService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tenant_id = 1 [json_name = "tenantId"];</code>
     * @return string
     */
    public function getTenantId()
    {
        return $this->tenant_id;
    }

    /**
     * Generated from protobuf field <code>string tenant_id = 1 [json_name = "tenantId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTenantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tenant_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string configuration_id = 2 [json_name = "configurationId"];</code>
     * @return string
     */
    public function getConfigurationId()
    {
        return $this->configuration_id;
    }

    /**
     * Generated from protobuf field <code>string configuration_id = 2 [json_name = "configurationId"];</code>
     * @param string $var
     * @return $this
     */
    public function setConfigurationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->configuration_id = $var;

        return $this;
    }

}

