<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sidecar/lti_service.proto

namespace Oat\Envmgmt\Sidecar;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.sidecar.GetRegistrationRequest</code>
 */
class GetRegistrationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string registration_id = 2 [json_name = "registrationId"];</code>
     */
    protected $registration_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $registration_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sidecar\LtiService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string registration_id = 2 [json_name = "registrationId"];</code>
     * @return string
     */
    public function getRegistrationId()
    {
        return $this->registration_id;
    }

    /**
     * Generated from protobuf field <code>string registration_id = 2 [json_name = "registrationId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRegistrationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->registration_id = $var;

        return $this;
    }

}

