<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sidecar/lti_service.proto

namespace Oat\Envmgmt\Sidecar;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.sidecar.ListRegistrationsRequest</code>
 */
class ListRegistrationsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     */
    protected $client_id = null;
    /**
     * Generated from protobuf field <code>string platform_issuer = 3 [json_name = "platformIssuer"];</code>
     */
    protected $platform_issuer = null;
    /**
     * Generated from protobuf field <code>string tool_issuer = 4 [json_name = "toolIssuer"];</code>
     */
    protected $tool_issuer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client_id
     *     @type string $platform_issuer
     *     @type string $tool_issuer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sidecar\LtiService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     * @return string
     */
    public function getClientId()
    {
        return isset($this->client_id) ? $this->client_id : '';
    }

    public function hasClientId()
    {
        return isset($this->client_id);
    }

    public function clearClientId()
    {
        unset($this->client_id);
    }

    /**
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platform_issuer = 3 [json_name = "platformIssuer"];</code>
     * @return string
     */
    public function getPlatformIssuer()
    {
        return isset($this->platform_issuer) ? $this->platform_issuer : '';
    }

    public function hasPlatformIssuer()
    {
        return isset($this->platform_issuer);
    }

    public function clearPlatformIssuer()
    {
        unset($this->platform_issuer);
    }

    /**
     * Generated from protobuf field <code>string platform_issuer = 3 [json_name = "platformIssuer"];</code>
     * @param string $var
     * @return $this
     */
    public function setPlatformIssuer($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform_issuer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tool_issuer = 4 [json_name = "toolIssuer"];</code>
     * @return string
     */
    public function getToolIssuer()
    {
        return isset($this->tool_issuer) ? $this->tool_issuer : '';
    }

    public function hasToolIssuer()
    {
        return isset($this->tool_issuer);
    }

    public function clearToolIssuer()
    {
        unset($this->tool_issuer);
    }

    /**
     * Generated from protobuf field <code>string tool_issuer = 4 [json_name = "toolIssuer"];</code>
     * @param string $var
     * @return $this
     */
    public function setToolIssuer($var)
    {
        GPBUtil::checkString($var, True);
        $this->tool_issuer = $var;

        return $this;
    }

}

