<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sidecar/oauth2_client_service.proto

namespace Oat\Envmgmt\Sidecar;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.sidecar.ValidateUserPasswordRequest</code>
 */
class ValidateUserPasswordRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.Oauth2UserPassword oauth2UserPassword = 1 [json_name = "oauth2UserPassword"];</code>
     */
    protected $oauth2UserPassword = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Oat\Envmgmt\Common\Oauth2UserPassword $oauth2UserPassword
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sidecar\Oauth2ClientService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.Oauth2UserPassword oauth2UserPassword = 1 [json_name = "oauth2UserPassword"];</code>
     * @return \Oat\Envmgmt\Common\Oauth2UserPassword|null
     */
    public function getOauth2UserPassword()
    {
        return isset($this->oauth2UserPassword) ? $this->oauth2UserPassword : null;
    }

    public function hasOauth2UserPassword()
    {
        return isset($this->oauth2UserPassword);
    }

    public function clearOauth2UserPassword()
    {
        unset($this->oauth2UserPassword);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.Oauth2UserPassword oauth2UserPassword = 1 [json_name = "oauth2UserPassword"];</code>
     * @param \Oat\Envmgmt\Common\Oauth2UserPassword $var
     * @return $this
     */
    public function setOauth2UserPassword($var)
    {
        GPBUtil::checkMessage($var, \Oat\Envmgmt\Common\Oauth2UserPassword::class);
        $this->oauth2UserPassword = $var;

        return $this;
    }

}

