<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sidecar/config_service.proto

namespace GPBMetadata\Sidecar;

class ConfigService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Configuration::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
ü
sidecar/config_service.protooat.envmgmt.sidecargoogle/api/annotations.proto"1
ListConfigsRequest
	tenant_id (	RtenantId"Z
GetConfigRequest
	tenant_id (	RtenantId)
configuration_id (	RconfigurationId2È
ConfigService—
ListConfigs\'.oat.envmgmt.sidecar.ListConfigsRequest+.oat.envmgmt.common.ConfigurationCollection"2‚Óä“,*/api/v1/tenants/{tenant_id}/configurationsœ
	GetConfig%.oat.envmgmt.sidecar.GetConfigRequest!.oat.envmgmt.common.Configuration"E‚Óä“?=/api/v1/tenants/{tenant_id}/configurations/{configuration_id}BGZEgithub.com/oat-sa/environment-management/libs/lib-em-go-proto/sidecarbproto3'
        , true);

        static::$is_initialized = true;
    }
}

