<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sidecar/feature_flag_service.proto

namespace GPBMetadata\Sidecar;

class FeatureFlagService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\FeatureFlag::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
›
"sidecar/feature_flag_service.protooat.envmgmt.sidecargoogle/api/annotations.proto"6
ListFeatureFlagsRequest
	tenant_id (	RtenantId"\\
GetFeatureFlagRequest
	tenant_id (	RtenantId&
feature_flag_id (	RfeatureFlagId2Ú
FeatureFlagServicež
ListFeatureFlags,.oat.envmgmt.sidecar.ListFeatureFlagsRequest).oat.envmgmt.common.FeatureFlagCollection"1‚Óä“+)/api/v1/tenants/{tenant_id}/feature-flags¢
GetFeatureFlag*.oat.envmgmt.sidecar.GetFeatureFlagRequest.oat.envmgmt.common.FeatureFlag"C‚Óä“=;/api/v1/tenants/{tenant_id}/feature-flags/{feature_flag_id}BGZEgithub.com/oat-sa/environment-management/libs/lib-em-go-proto/sidecarbproto3'
        , true);

        static::$is_initialized = true;
    }
}

