<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/account.proto

namespace GPBMetadata\Common;

class Account
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Configuration::initOnce();
        \GPBMetadata\Common\FeatureFlag::initOnce();
        \GPBMetadata\Common\LtiPlatform::initOnce();
        \GPBMetadata\Common\LtiTool::initOnce();
        \GPBMetadata\Common\LtiRegistration::initOnce();
        \GPBMetadata\Common\Oauth2Client::initOnce();
        $pool->internalAddGeneratedFile(
            '
¬
common/account.protooat.envmgmt.commoncommon/feature_flag.protocommon/lti_platform.protocommon/lti_tool.protocommon/lti_registration.protocommon/oauth2_client.proto"u
AccountMeta
id (	Rid
name (	Rname%
environment_id (	RenvironmentId
	parent_id (	RparentId"ê
Account3
meta (2.oat.envmgmt.common.AccountMetaRmetaD
feature_flags (2.oat.envmgmt.common.FeatureFlagRfeatureFlagsI
configurations (2!.oat.envmgmt.common.ConfigurationRconfigurationsD
lti_platforms (2.oat.envmgmt.common.LtiPlatformRltiPlatforms8
	lti_tools (2.oat.envmgmt.common.LtiToolRltiToolsP
lti_registrations (2#.oat.envmgmt.common.LtiRegistrationRltiRegistrationsG
oauth2_clients (2 .oat.envmgmt.common.Oauth2ClientRoauth2Clients"D
AccountCollection/
data (2.oat.envmgmt.common.AccountRdataBFZDgithub.com/oat-sa/environment-management/libs/lib-em-go-proto/commonbproto3'
        , true);

        static::$is_initialized = true;
    }
}

