<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/environment.proto

namespace GPBMetadata\Common;

class Environment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Configuration::initOnce();
        \GPBMetadata\Common\FeatureFlag::initOnce();
        \GPBMetadata\Common\LtiPlatform::initOnce();
        \GPBMetadata\Common\LtiTool::initOnce();
        \GPBMetadata\Common\LtiRegistration::initOnce();
        \GPBMetadata\Common\Oauth2Client::initOnce();
        $pool->internalAddGeneratedFile(
            '
€
common/environment.protooat.envmgmt.commoncommon/feature_flag.protocommon/lti_platform.protocommon/lti_tool.protocommon/lti_registration.protocommon/oauth2_client.proto"5
EnvironmentMeta
id (	Rid
name (	Rname"ò
Environment7
meta (2#.oat.envmgmt.common.EnvironmentMetaRmetaD
feature_flags (2.oat.envmgmt.common.FeatureFlagRfeatureFlagsI
configurations (2!.oat.envmgmt.common.ConfigurationRconfigurationsD
lti_platforms (2.oat.envmgmt.common.LtiPlatformRltiPlatforms8
	lti_tools (2.oat.envmgmt.common.LtiToolRltiToolsP
lti_registrations (2#.oat.envmgmt.common.LtiRegistrationRltiRegistrationsG
oauth2_clients (2 .oat.envmgmt.common.Oauth2ClientRoauth2Clients"L
EnvironmentCollection3
data (2.oat.envmgmt.common.EnvironmentRdataBFZDgithub.com/oat-sa/environment-management/libs/lib-em-go-proto/commonbproto3'
        , true);

        static::$is_initialized = true;
    }
}

