<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/instance.proto

namespace GPBMetadata\Common;

class Instance
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
·
common/instance.protooat.envmgmt.common"0
InstanceMeta
id (	Rid
url (	Rurl"@
Instance4
meta (2 .oat.envmgmt.common.InstanceMetaRmeta"F
InstanceCollection0
data (2.oat.envmgmt.common.InstanceRdataBFZDgithub.com/oat-sa/environment-management/libs/lib-em-go-proto/commonbproto3'
        , true);

        static::$is_initialized = true;
    }
}

