<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/lti_key_chain.proto

namespace GPBMetadata\Common;

class LtiKeyChain
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¸
common/lti_key_chain.protooat.envmgmt.common"µ
LtiKeyChain
id (	Rid 
key_set_name (	R
keySetName

public_key (	R	publicKey
private_key (	R
privateKey4
private_key_passphrase (	RprivateKeyPassphraseBFZDgithub.com/oat-sa/environment-management/libs/lib-em-go-proto/commonbproto3'
        , true);

        static::$is_initialized = true;
    }
}

