<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/tenant.proto

namespace GPBMetadata\Common;

class Tenant
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Configuration::initOnce();
        \GPBMetadata\Common\FeatureFlag::initOnce();
        \GPBMetadata\Common\LtiPlatform::initOnce();
        \GPBMetadata\Common\LtiTool::initOnce();
        \GPBMetadata\Common\LtiRegistration::initOnce();
        \GPBMetadata\Common\Oauth2Client::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ž
common/tenant.protooat.envmgmt.commoncommon/feature_flag.protocommon/lti_platform.protocommon/lti_tool.protocommon/lti_registration.protocommon/oauth2_client.proto"\\

TenantMeta
id (	Rid

account_id (	R	accountId
instance_id (	R
instanceId"è
Tenant2
meta (2.oat.envmgmt.common.TenantMetaRmetaD
feature_flags (2.oat.envmgmt.common.FeatureFlagRfeatureFlagsI
configurations (2!.oat.envmgmt.common.ConfigurationRconfigurationsD
lti_platforms (2.oat.envmgmt.common.LtiPlatformRltiPlatforms8
	lti_tools (2.oat.envmgmt.common.LtiToolRltiToolsP
lti_registrations (2#.oat.envmgmt.common.LtiRegistrationRltiRegistrationsG
oauth2_clients (2 .oat.envmgmt.common.Oauth2ClientRoauth2Clients"B
TenantCollection.
data (2.oat.envmgmt.common.TenantRdataBFZDgithub.com/oat-sa/environment-management/libs/lib-em-go-proto/commonbproto3'
        , true);

        static::$is_initialized = true;
    }
}

