<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/feature_flag.proto

namespace Oat\Envmgmt\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.common.FeatureFlag</code>
 */
class FeatureFlag extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string value = 2 [json_name = "value"];</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>string owner_id = 3 [json_name = "ownerId"];</code>
     */
    protected $owner_id = null;
    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.OwnerType owner_type = 4 [json_name = "ownerType"];</code>
     */
    protected $owner_type = null;
    /**
     * Generated from protobuf field <code>bool tracked = 5 [json_name = "tracked"];</code>
     */
    protected $tracked = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $value
     *     @type string $owner_id
     *     @type int $owner_type
     *     @type bool $tracked
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\FeatureFlag::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 2 [json_name = "value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 2 [json_name = "value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 3 [json_name = "ownerId"];</code>
     * @return string
     */
    public function getOwnerId()
    {
        return isset($this->owner_id) ? $this->owner_id : '';
    }

    public function hasOwnerId()
    {
        return isset($this->owner_id);
    }

    public function clearOwnerId()
    {
        unset($this->owner_id);
    }

    /**
     * Generated from protobuf field <code>string owner_id = 3 [json_name = "ownerId"];</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.OwnerType owner_type = 4 [json_name = "ownerType"];</code>
     * @return int
     */
    public function getOwnerType()
    {
        return isset($this->owner_type) ? $this->owner_type : 0;
    }

    public function hasOwnerType()
    {
        return isset($this->owner_type);
    }

    public function clearOwnerType()
    {
        unset($this->owner_type);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.OwnerType owner_type = 4 [json_name = "ownerType"];</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerType($var)
    {
        GPBUtil::checkEnum($var, \Oat\Envmgmt\Common\OwnerType::class);
        $this->owner_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool tracked = 5 [json_name = "tracked"];</code>
     * @return bool
     */
    public function getTracked()
    {
        return isset($this->tracked) ? $this->tracked : false;
    }

    public function hasTracked()
    {
        return isset($this->tracked);
    }

    public function clearTracked()
    {
        unset($this->tracked);
    }

    /**
     * Generated from protobuf field <code>bool tracked = 5 [json_name = "tracked"];</code>
     * @param bool $var
     * @return $this
     */
    public function setTracked($var)
    {
        GPBUtil::checkBool($var);
        $this->tracked = $var;

        return $this;
    }

}

