<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/instance.proto

namespace Oat\Envmgmt\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.common.Instance</code>
 */
class Instance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.InstanceMeta meta = 1 [json_name = "meta"];</code>
     */
    protected $meta = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Oat\Envmgmt\Common\InstanceMeta $meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Instance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.InstanceMeta meta = 1 [json_name = "meta"];</code>
     * @return \Oat\Envmgmt\Common\InstanceMeta|null
     */
    public function getMeta()
    {
        return isset($this->meta) ? $this->meta : null;
    }

    public function hasMeta()
    {
        return isset($this->meta);
    }

    public function clearMeta()
    {
        unset($this->meta);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.InstanceMeta meta = 1 [json_name = "meta"];</code>
     * @param \Oat\Envmgmt\Common\InstanceMeta $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkMessage($var, \Oat\Envmgmt\Common\InstanceMeta::class);
        $this->meta = $var;

        return $this;
    }

}

