<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/lti_key_chain.proto

namespace Oat\Envmgmt\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.common.LtiKeyChain</code>
 */
class LtiKeyChain extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string key_set_name = 2 [json_name = "keySetName"];</code>
     */
    protected $key_set_name = '';
    /**
     * Generated from protobuf field <code>string public_key = 3 [json_name = "publicKey"];</code>
     */
    protected $public_key = '';
    /**
     * Generated from protobuf field <code>string private_key = 4 [json_name = "privateKey"];</code>
     */
    protected $private_key = null;
    /**
     * Generated from protobuf field <code>string private_key_passphrase = 5 [json_name = "privateKeyPassphrase"];</code>
     */
    protected $private_key_passphrase = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $key_set_name
     *     @type string $public_key
     *     @type string $private_key
     *     @type string $private_key_passphrase
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\LtiKeyChain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key_set_name = 2 [json_name = "keySetName"];</code>
     * @return string
     */
    public function getKeySetName()
    {
        return $this->key_set_name;
    }

    /**
     * Generated from protobuf field <code>string key_set_name = 2 [json_name = "keySetName"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeySetName($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_set_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string public_key = 3 [json_name = "publicKey"];</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>string public_key = 3 [json_name = "publicKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string private_key = 4 [json_name = "privateKey"];</code>
     * @return string
     */
    public function getPrivateKey()
    {
        return isset($this->private_key) ? $this->private_key : '';
    }

    public function hasPrivateKey()
    {
        return isset($this->private_key);
    }

    public function clearPrivateKey()
    {
        unset($this->private_key);
    }

    /**
     * Generated from protobuf field <code>string private_key = 4 [json_name = "privateKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->private_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string private_key_passphrase = 5 [json_name = "privateKeyPassphrase"];</code>
     * @return string
     */
    public function getPrivateKeyPassphrase()
    {
        return isset($this->private_key_passphrase) ? $this->private_key_passphrase : '';
    }

    public function hasPrivateKeyPassphrase()
    {
        return isset($this->private_key_passphrase);
    }

    public function clearPrivateKeyPassphrase()
    {
        unset($this->private_key_passphrase);
    }

    /**
     * Generated from protobuf field <code>string private_key_passphrase = 5 [json_name = "privateKeyPassphrase"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKeyPassphrase($var)
    {
        GPBUtil::checkString($var, True);
        $this->private_key_passphrase = $var;

        return $this;
    }

}

