<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/lti_registration.proto

namespace Oat\Envmgmt\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.common.LtiRegistration</code>
 */
class LtiRegistration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     */
    protected $client_id = '';
    /**
     * Generated from protobuf field <code>string platform_id = 3 [json_name = "platformId"];</code>
     */
    protected $platform_id = '';
    /**
     * Generated from protobuf field <code>string tool_id = 4 [json_name = "toolId"];</code>
     */
    protected $tool_id = '';
    /**
     * Generated from protobuf field <code>repeated string deployment_ids = 9 [json_name = "deploymentIds"];</code>
     */
    private $deployment_ids;
    /**
     * Generated from protobuf field <code>string platform_jwks_url = 5 [json_name = "platformJwksUrl"];</code>
     */
    protected $platform_jwks_url = null;
    /**
     * Generated from protobuf field <code>string tool_jwks_url = 6 [json_name = "toolJwksUrl"];</code>
     */
    protected $tool_jwks_url = null;
    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiKeyChain platform_key_chain = 7 [json_name = "platformKeyChain"];</code>
     */
    protected $platform_key_chain = null;
    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiKeyChain tool_key_chain = 8 [json_name = "toolKeyChain"];</code>
     */
    protected $tool_key_chain = null;
    /**
     * Generated from protobuf field <code>string owner_id = 10 [json_name = "ownerId"];</code>
     */
    protected $owner_id = null;
    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.OwnerType owner_type = 11 [json_name = "ownerType"];</code>
     */
    protected $owner_type = null;
    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiTool tool = 12 [json_name = "tool"];</code>
     */
    protected $tool = null;
    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiPlatform platform = 13 [json_name = "platform"];</code>
     */
    protected $platform = null;
    /**
     * Generated from protobuf field <code>string tenant_id = 14 [json_name = "tenantId"];</code>
     */
    protected $tenant_id = null;
    /**
     * Generated from protobuf field <code>string client_secret = 15 [json_name = "clientSecret"];</code>
     */
    protected $client_secret = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $client_id
     *     @type string $platform_id
     *     @type string $tool_id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $deployment_ids
     *     @type string $platform_jwks_url
     *     @type string $tool_jwks_url
     *     @type \Oat\Envmgmt\Common\LtiKeyChain $platform_key_chain
     *     @type \Oat\Envmgmt\Common\LtiKeyChain $tool_key_chain
     *     @type string $owner_id
     *     @type int $owner_type
     *     @type \Oat\Envmgmt\Common\LtiTool $tool
     *     @type \Oat\Envmgmt\Common\LtiPlatform $platform
     *     @type string $tenant_id
     *     @type string $client_secret
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\LtiRegistration::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platform_id = 3 [json_name = "platformId"];</code>
     * @return string
     */
    public function getPlatformId()
    {
        return $this->platform_id;
    }

    /**
     * Generated from protobuf field <code>string platform_id = 3 [json_name = "platformId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPlatformId($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tool_id = 4 [json_name = "toolId"];</code>
     * @return string
     */
    public function getToolId()
    {
        return $this->tool_id;
    }

    /**
     * Generated from protobuf field <code>string tool_id = 4 [json_name = "toolId"];</code>
     * @param string $var
     * @return $this
     */
    public function setToolId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tool_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string deployment_ids = 9 [json_name = "deploymentIds"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeploymentIds()
    {
        return $this->deployment_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string deployment_ids = 9 [json_name = "deploymentIds"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeploymentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->deployment_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platform_jwks_url = 5 [json_name = "platformJwksUrl"];</code>
     * @return string
     */
    public function getPlatformJwksUrl()
    {
        return isset($this->platform_jwks_url) ? $this->platform_jwks_url : '';
    }

    public function hasPlatformJwksUrl()
    {
        return isset($this->platform_jwks_url);
    }

    public function clearPlatformJwksUrl()
    {
        unset($this->platform_jwks_url);
    }

    /**
     * Generated from protobuf field <code>string platform_jwks_url = 5 [json_name = "platformJwksUrl"];</code>
     * @param string $var
     * @return $this
     */
    public function setPlatformJwksUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform_jwks_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tool_jwks_url = 6 [json_name = "toolJwksUrl"];</code>
     * @return string
     */
    public function getToolJwksUrl()
    {
        return isset($this->tool_jwks_url) ? $this->tool_jwks_url : '';
    }

    public function hasToolJwksUrl()
    {
        return isset($this->tool_jwks_url);
    }

    public function clearToolJwksUrl()
    {
        unset($this->tool_jwks_url);
    }

    /**
     * Generated from protobuf field <code>string tool_jwks_url = 6 [json_name = "toolJwksUrl"];</code>
     * @param string $var
     * @return $this
     */
    public function setToolJwksUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->tool_jwks_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiKeyChain platform_key_chain = 7 [json_name = "platformKeyChain"];</code>
     * @return \Oat\Envmgmt\Common\LtiKeyChain|null
     */
    public function getPlatformKeyChain()
    {
        return isset($this->platform_key_chain) ? $this->platform_key_chain : null;
    }

    public function hasPlatformKeyChain()
    {
        return isset($this->platform_key_chain);
    }

    public function clearPlatformKeyChain()
    {
        unset($this->platform_key_chain);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiKeyChain platform_key_chain = 7 [json_name = "platformKeyChain"];</code>
     * @param \Oat\Envmgmt\Common\LtiKeyChain $var
     * @return $this
     */
    public function setPlatformKeyChain($var)
    {
        GPBUtil::checkMessage($var, \Oat\Envmgmt\Common\LtiKeyChain::class);
        $this->platform_key_chain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiKeyChain tool_key_chain = 8 [json_name = "toolKeyChain"];</code>
     * @return \Oat\Envmgmt\Common\LtiKeyChain|null
     */
    public function getToolKeyChain()
    {
        return isset($this->tool_key_chain) ? $this->tool_key_chain : null;
    }

    public function hasToolKeyChain()
    {
        return isset($this->tool_key_chain);
    }

    public function clearToolKeyChain()
    {
        unset($this->tool_key_chain);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiKeyChain tool_key_chain = 8 [json_name = "toolKeyChain"];</code>
     * @param \Oat\Envmgmt\Common\LtiKeyChain $var
     * @return $this
     */
    public function setToolKeyChain($var)
    {
        GPBUtil::checkMessage($var, \Oat\Envmgmt\Common\LtiKeyChain::class);
        $this->tool_key_chain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 10 [json_name = "ownerId"];</code>
     * @return string
     */
    public function getOwnerId()
    {
        return isset($this->owner_id) ? $this->owner_id : '';
    }

    public function hasOwnerId()
    {
        return isset($this->owner_id);
    }

    public function clearOwnerId()
    {
        unset($this->owner_id);
    }

    /**
     * Generated from protobuf field <code>string owner_id = 10 [json_name = "ownerId"];</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.OwnerType owner_type = 11 [json_name = "ownerType"];</code>
     * @return int
     */
    public function getOwnerType()
    {
        return isset($this->owner_type) ? $this->owner_type : 0;
    }

    public function hasOwnerType()
    {
        return isset($this->owner_type);
    }

    public function clearOwnerType()
    {
        unset($this->owner_type);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.OwnerType owner_type = 11 [json_name = "ownerType"];</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerType($var)
    {
        GPBUtil::checkEnum($var, \Oat\Envmgmt\Common\OwnerType::class);
        $this->owner_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiTool tool = 12 [json_name = "tool"];</code>
     * @return \Oat\Envmgmt\Common\LtiTool|null
     */
    public function getTool()
    {
        return isset($this->tool) ? $this->tool : null;
    }

    public function hasTool()
    {
        return isset($this->tool);
    }

    public function clearTool()
    {
        unset($this->tool);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiTool tool = 12 [json_name = "tool"];</code>
     * @param \Oat\Envmgmt\Common\LtiTool $var
     * @return $this
     */
    public function setTool($var)
    {
        GPBUtil::checkMessage($var, \Oat\Envmgmt\Common\LtiTool::class);
        $this->tool = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiPlatform platform = 13 [json_name = "platform"];</code>
     * @return \Oat\Envmgmt\Common\LtiPlatform|null
     */
    public function getPlatform()
    {
        return isset($this->platform) ? $this->platform : null;
    }

    public function hasPlatform()
    {
        return isset($this->platform);
    }

    public function clearPlatform()
    {
        unset($this->platform);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.LtiPlatform platform = 13 [json_name = "platform"];</code>
     * @param \Oat\Envmgmt\Common\LtiPlatform $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkMessage($var, \Oat\Envmgmt\Common\LtiPlatform::class);
        $this->platform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tenant_id = 14 [json_name = "tenantId"];</code>
     * @return string
     */
    public function getTenantId()
    {
        return isset($this->tenant_id) ? $this->tenant_id : '';
    }

    public function hasTenantId()
    {
        return isset($this->tenant_id);
    }

    public function clearTenantId()
    {
        unset($this->tenant_id);
    }

    /**
     * Generated from protobuf field <code>string tenant_id = 14 [json_name = "tenantId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTenantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tenant_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 15 [json_name = "clientSecret"];</code>
     * @return string
     */
    public function getClientSecret()
    {
        return isset($this->client_secret) ? $this->client_secret : '';
    }

    public function hasClientSecret()
    {
        return isset($this->client_secret);
    }

    public function clearClientSecret()
    {
        unset($this->client_secret);
    }

    /**
     * Generated from protobuf field <code>string client_secret = 15 [json_name = "clientSecret"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_secret = $var;

        return $this;
    }

}

