<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/oauth2_client.proto

namespace Oat\Envmgmt\Common;

use UnexpectedValueException;

/**
 * Protobuf type <code>oat.envmgmt.common.Oauth2UsersSource</code>
 */
class Oauth2UsersSource
{
    /**
     * Generated from protobuf enum <code>LOCAL = 0;</code>
     */
    const LOCAL = 0;
    /**
     * Generated from protobuf enum <code>PORTAL = 1;</code>
     */
    const PORTAL = 1;
    /**
     * Generated from protobuf enum <code>SCORING = 2;</code>
     */
    const SCORING = 2;

    private static $valueToName = [
        self::LOCAL => 'LOCAL',
        self::PORTAL => 'PORTAL',
        self::SCORING => 'SCORING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

