<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/oauth2_client.proto

namespace Oat\Envmgmt\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.common.Oauth2ClientCollection</code>
 */
class Oauth2ClientCollection extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.Oauth2Client data = 1 [json_name = "data"];</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Oat\Envmgmt\Common\Oauth2Client[]|\Google\Protobuf\Internal\RepeatedField $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Oauth2Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.Oauth2Client data = 1 [json_name = "data"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.Oauth2Client data = 1 [json_name = "data"];</code>
     * @param \Oat\Envmgmt\Common\Oauth2Client[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Oat\Envmgmt\Common\Oauth2Client::class);
        $this->data = $arr;

        return $this;
    }

}

