<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/oauth2_client.proto

namespace Oat\Envmgmt\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.common.Oauth2Client</code>
 */
class Oauth2Client extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     */
    protected $client_id = '';
    /**
     * Generated from protobuf field <code>string client_secret = 3 [json_name = "clientSecret"];</code>
     */
    protected $client_secret = '';
    /**
     * Generated from protobuf field <code>repeated string scopes = 4 [json_name = "scopes"];</code>
     */
    private $scopes;
    /**
     * Generated from protobuf field <code>string tenant_id = 5 [json_name = "tenantId"];</code>
     */
    protected $tenant_id = null;
    /**
     * Generated from protobuf field <code>string instance_url = 6 [json_name = "instanceUrl"];</code>
     */
    protected $instance_url = null;
    /**
     * Generated from protobuf field <code>string owner_id = 7 [json_name = "ownerId"];</code>
     */
    protected $owner_id = null;
    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.OwnerType owner_type = 8 [json_name = "ownerType"];</code>
     */
    protected $owner_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $client_id
     *     @type string $client_secret
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $scopes
     *     @type string $tenant_id
     *     @type string $instance_url
     *     @type string $owner_id
     *     @type int $owner_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Oauth2Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 3 [json_name = "clientSecret"];</code>
     * @return string
     */
    public function getClientSecret()
    {
        return $this->client_secret;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 3 [json_name = "clientSecret"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_secret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string scopes = 4 [json_name = "scopes"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    /**
     * Generated from protobuf field <code>repeated string scopes = 4 [json_name = "scopes"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scopes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tenant_id = 5 [json_name = "tenantId"];</code>
     * @return string
     */
    public function getTenantId()
    {
        return isset($this->tenant_id) ? $this->tenant_id : '';
    }

    public function hasTenantId()
    {
        return isset($this->tenant_id);
    }

    public function clearTenantId()
    {
        unset($this->tenant_id);
    }

    /**
     * Generated from protobuf field <code>string tenant_id = 5 [json_name = "tenantId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTenantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tenant_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string instance_url = 6 [json_name = "instanceUrl"];</code>
     * @return string
     */
    public function getInstanceUrl()
    {
        return isset($this->instance_url) ? $this->instance_url : '';
    }

    public function hasInstanceUrl()
    {
        return isset($this->instance_url);
    }

    public function clearInstanceUrl()
    {
        unset($this->instance_url);
    }

    /**
     * Generated from protobuf field <code>string instance_url = 6 [json_name = "instanceUrl"];</code>
     * @param string $var
     * @return $this
     */
    public function setInstanceUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->instance_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 7 [json_name = "ownerId"];</code>
     * @return string
     */
    public function getOwnerId()
    {
        return isset($this->owner_id) ? $this->owner_id : '';
    }

    public function hasOwnerId()
    {
        return isset($this->owner_id);
    }

    public function clearOwnerId()
    {
        unset($this->owner_id);
    }

    /**
     * Generated from protobuf field <code>string owner_id = 7 [json_name = "ownerId"];</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.OwnerType owner_type = 8 [json_name = "ownerType"];</code>
     * @return int
     */
    public function getOwnerType()
    {
        return isset($this->owner_type) ? $this->owner_type : 0;
    }

    public function hasOwnerType()
    {
        return isset($this->owner_type);
    }

    public function clearOwnerType()
    {
        unset($this->owner_type);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.OwnerType owner_type = 8 [json_name = "ownerType"];</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerType($var)
    {
        GPBUtil::checkEnum($var, \Oat\Envmgmt\Common\OwnerType::class);
        $this->owner_type = $var;

        return $this;
    }

}

