<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/oauth2_client.proto

namespace Oat\Envmgmt\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.common.PasswordValidation</code>
 */
class PasswordValidation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool valid = 1 [json_name = "valid"];</code>
     */
    protected $valid = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $valid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Oauth2Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool valid = 1 [json_name = "valid"];</code>
     * @return bool
     */
    public function getValid()
    {
        return $this->valid;
    }

    /**
     * Generated from protobuf field <code>bool valid = 1 [json_name = "valid"];</code>
     * @param bool $var
     * @return $this
     */
    public function setValid($var)
    {
        GPBUtil::checkBool($var);
        $this->valid = $var;

        return $this;
    }

}

