<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/tenant.proto

namespace Oat\Envmgmt\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.common.Tenant</code>
 */
class Tenant extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.TenantMeta meta = 1 [json_name = "meta"];</code>
     */
    protected $meta = null;
    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.FeatureFlag feature_flags = 2 [json_name = "featureFlags"];</code>
     */
    private $feature_flags;
    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.Configuration configurations = 3 [json_name = "configurations"];</code>
     */
    private $configurations;
    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.LtiPlatform lti_platforms = 4 [json_name = "ltiPlatforms"];</code>
     */
    private $lti_platforms;
    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.LtiTool lti_tools = 5 [json_name = "ltiTools"];</code>
     */
    private $lti_tools;
    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.LtiRegistration lti_registrations = 6 [json_name = "ltiRegistrations"];</code>
     */
    private $lti_registrations;
    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.Oauth2Client oauth2_clients = 7 [json_name = "oauth2Clients"];</code>
     */
    private $oauth2_clients;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Oat\Envmgmt\Common\TenantMeta $meta
     *     @type \Oat\Envmgmt\Common\FeatureFlag[]|\Google\Protobuf\Internal\RepeatedField $feature_flags
     *     @type \Oat\Envmgmt\Common\Configuration[]|\Google\Protobuf\Internal\RepeatedField $configurations
     *     @type \Oat\Envmgmt\Common\LtiPlatform[]|\Google\Protobuf\Internal\RepeatedField $lti_platforms
     *     @type \Oat\Envmgmt\Common\LtiTool[]|\Google\Protobuf\Internal\RepeatedField $lti_tools
     *     @type \Oat\Envmgmt\Common\LtiRegistration[]|\Google\Protobuf\Internal\RepeatedField $lti_registrations
     *     @type \Oat\Envmgmt\Common\Oauth2Client[]|\Google\Protobuf\Internal\RepeatedField $oauth2_clients
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Tenant::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.TenantMeta meta = 1 [json_name = "meta"];</code>
     * @return \Oat\Envmgmt\Common\TenantMeta|null
     */
    public function getMeta()
    {
        return isset($this->meta) ? $this->meta : null;
    }

    public function hasMeta()
    {
        return isset($this->meta);
    }

    public function clearMeta()
    {
        unset($this->meta);
    }

    /**
     * Generated from protobuf field <code>.oat.envmgmt.common.TenantMeta meta = 1 [json_name = "meta"];</code>
     * @param \Oat\Envmgmt\Common\TenantMeta $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkMessage($var, \Oat\Envmgmt\Common\TenantMeta::class);
        $this->meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.FeatureFlag feature_flags = 2 [json_name = "featureFlags"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFeatureFlags()
    {
        return $this->feature_flags;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.FeatureFlag feature_flags = 2 [json_name = "featureFlags"];</code>
     * @param \Oat\Envmgmt\Common\FeatureFlag[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFeatureFlags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Oat\Envmgmt\Common\FeatureFlag::class);
        $this->feature_flags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.Configuration configurations = 3 [json_name = "configurations"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConfigurations()
    {
        return $this->configurations;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.Configuration configurations = 3 [json_name = "configurations"];</code>
     * @param \Oat\Envmgmt\Common\Configuration[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConfigurations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Oat\Envmgmt\Common\Configuration::class);
        $this->configurations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.LtiPlatform lti_platforms = 4 [json_name = "ltiPlatforms"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLtiPlatforms()
    {
        return $this->lti_platforms;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.LtiPlatform lti_platforms = 4 [json_name = "ltiPlatforms"];</code>
     * @param \Oat\Envmgmt\Common\LtiPlatform[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLtiPlatforms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Oat\Envmgmt\Common\LtiPlatform::class);
        $this->lti_platforms = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.LtiTool lti_tools = 5 [json_name = "ltiTools"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLtiTools()
    {
        return $this->lti_tools;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.LtiTool lti_tools = 5 [json_name = "ltiTools"];</code>
     * @param \Oat\Envmgmt\Common\LtiTool[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLtiTools($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Oat\Envmgmt\Common\LtiTool::class);
        $this->lti_tools = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.LtiRegistration lti_registrations = 6 [json_name = "ltiRegistrations"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLtiRegistrations()
    {
        return $this->lti_registrations;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.LtiRegistration lti_registrations = 6 [json_name = "ltiRegistrations"];</code>
     * @param \Oat\Envmgmt\Common\LtiRegistration[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLtiRegistrations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Oat\Envmgmt\Common\LtiRegistration::class);
        $this->lti_registrations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.Oauth2Client oauth2_clients = 7 [json_name = "oauth2Clients"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOauth2Clients()
    {
        return $this->oauth2_clients;
    }

    /**
     * Generated from protobuf field <code>repeated .oat.envmgmt.common.Oauth2Client oauth2_clients = 7 [json_name = "oauth2Clients"];</code>
     * @param \Oat\Envmgmt\Common\Oauth2Client[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOauth2Clients($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Oat\Envmgmt\Common\Oauth2Client::class);
        $this->oauth2_clients = $arr;

        return $this;
    }

}

