<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/oauth2_client.proto

namespace Oat\Envmgmt\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oat.envmgmt.common.ValidationResult</code>
 */
class ValidationResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_valid = 1 [json_name = "isValid"];</code>
     */
    protected $is_valid = false;
    /**
     * Generated from protobuf field <code>string errorMsg = 2 [json_name = "errorMsg"];</code>
     */
    protected $errorMsg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_valid
     *     @type string $errorMsg
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Oauth2Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_valid = 1 [json_name = "isValid"];</code>
     * @return bool
     */
    public function getIsValid()
    {
        return $this->is_valid;
    }

    /**
     * Generated from protobuf field <code>bool is_valid = 1 [json_name = "isValid"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsValid($var)
    {
        GPBUtil::checkBool($var);
        $this->is_valid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string errorMsg = 2 [json_name = "errorMsg"];</code>
     * @return string
     */
    public function getErrorMsg()
    {
        return $this->errorMsg;
    }

    /**
     * Generated from protobuf field <code>string errorMsg = 2 [json_name = "errorMsg"];</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->errorMsg = $var;

        return $this;
    }

}

