<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin/account_service.proto

namespace GPBMetadata\Admin;

class AccountService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Account::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
‡
admin/account_service.protooat.envmgmt.admingoogle/protobuf/empty.protogoogle/api/annotations.proto"M
CreateAccountRequest5
account (2.oat.envmgmt.common.AccountRaccount"#
GetAccountRequest
id (	Rid"0
ListAccountFeatureFlagsRequest
id (	Rid"+
ListAccountConfigsRequest
id (	Rid"]
UpdateAccountRequest
id (	Rid5
account (2.oat.envmgmt.common.AccountRaccount"&
DeleteAccountRequest
id (	Rid2…
AccountServiceg
ListAccounts.google.protobuf.Empty%.oat.envmgmt.common.AccountCollection"Ç”‰ì/api/v1/accountss
CreateAccount\'.oat.envmgmt.admin.CreateAccountRequest.google.protobuf.Empty"!Ç”‰ì"/api/v1/accounts:accountn

GetAccount$.oat.envmgmt.admin.GetAccountRequest.oat.envmgmt.common.Account"Ç”‰ì/api/v1/accounts/{id}x
UpdateAccount\'.oat.envmgmt.admin.UpdateAccountRequest.google.protobuf.Empty"&Ç”‰ì /api/v1/accounts/{id}:accounto
DeleteAccount\'.oat.envmgmt.admin.DeleteAccountRequest.google.protobuf.Empty"Ç”‰ì*/api/v1/accounts/{id}BEZCgithub.com/oat-sa/environment-management/libs/lib-em-go-proto/adminbproto3'
        , true);

        static::$is_initialized = true;
    }
}

