<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin/tenant_service.proto

namespace GPBMetadata\Admin;

class TenantService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Tenant::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
•	
admin/tenant_service.protooat.envmgmt.admingoogle/protobuf/empty.protogoogle/api/annotations.proto"I
CreateTenantRequest2
tenant (2.oat.envmgmt.common.TenantRtenant"T
ListTenantsRequest

account_id (	R	accountId
instance_id (	R
instanceId""
GetTenantRequest
id (	Rid"/
ListTenantFeatureFlagsRequest
id (	Rid"*
ListTenantConfigsRequest
id (	Rid"Y
UpdateTenantRequest
id (	Rid2
tenant (2.oat.envmgmt.common.TenantRtenant"%
DeleteTenantRequest
id (	Rid2≈
TenantServices
ListTenants%.oat.envmgmt.admin.ListTenantsRequest$.oat.envmgmt.common.TenantCollection"Ç”‰ì/api/v1/tenantso
CreateTenant&.oat.envmgmt.admin.CreateTenantRequest.google.protobuf.Empty"Ç”‰ì"/api/v1/tenants:tenantj
	GetTenant#.oat.envmgmt.admin.GetTenantRequest.oat.envmgmt.common.Tenant"Ç”‰ì/api/v1/tenants/{id}t
UpdateTenant&.oat.envmgmt.admin.UpdateTenantRequest.google.protobuf.Empty"$Ç”‰ì/api/v1/tenants/{id}:tenantl
DeleteTenant&.oat.envmgmt.admin.DeleteTenantRequest.google.protobuf.Empty"Ç”‰ì*/api/v1/tenants/{id}BEZCgithub.com/oat-sa/environment-management/libs/lib-em-go-proto/adminbproto3'
        , true);

        static::$is_initialized = true;
    }
}

